Models/ErrorViewModel.cs
namespace ListaTarefas.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Tarefa.cs
namespace ListaTarefas.Models
{
    public class Tarefa
    {
        public int TarefaId { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public DateTime Inicio { get; set; }
        public DateTime Fim { get; set; }
        public string Importancia { get; set; }
    }
}

Models/TarefaContext.cs
using Microsoft.EntityFrameworkCore;

namespace ListaTarefas.Models
{
    public class TarefaContext : DbContext
    {
        public DbSet<Tarefa> Tarefas { get; set; }
        public TarefaContext(DbContextOptions<TarefaContext> options) : base(options)
        {}
    }
}

Controllers/HomeController.cs
using ListaTarefas.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ListaTarefas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/TarefasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ListaTarefas.Models;

namespace ListaTarefas.Controllers
{
    public class TarefasController : Controller
    {
        private readonly TarefaContext _context;

        public TarefasController(TarefaContext context)
        {
            _context = context;
        }

        // GET: Tarefas
        public async Task<IActionResult> Index()
        {
              return View(await _context.Tarefas.ToListAsync());
        }

        // GET: Tarefas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Tarefas == null)
            {
                return NotFound();
            }

            var tarefa = await _context.Tarefas
                .FirstOrDefaultAsync(m => m.TarefaId == id);
            if (tarefa == null)
            {
                return NotFound();
            }

            return View(tarefa);
        }

        // GET: Tarefas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tarefas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TarefaId,Nome,Descricao,Inicio,Fim,Importancia")] Tarefa tarefa)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tarefa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tarefa);
        }

        // GET: Tarefas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Tarefas == null)
            {
                return NotFound();
            }

            var tarefa = await _context.Tarefas.FindAsync(id);
            if (tarefa == null)
            {
                return NotFound();
            }
            return View(tarefa);
        }

        // POST: Tarefas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TarefaId,Nome,Descricao,Inicio,Fim,Importancia")] Tarefa tarefa)
        {
            if (id != tarefa.TarefaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tarefa);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TarefaExists(tarefa.TarefaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tarefa);
        }

        // GET: Tarefas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Tarefas == null)
            {
                return NotFound();
            }

            var tarefa = await _context.Tarefas
                .FirstOrDefaultAsync(m => m.TarefaId == id);
            if (tarefa == null)
            {
                return NotFound();
            }

            return View(tarefa);
        }

        // POST: Tarefas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Tarefas == null)
            {
                return Problem("Entity set 'TarefaContext.Tarefas'  is null.");
            }
            var tarefa = await _context.Tarefas.FindAsync(id);
            if (tarefa != null)
            {
                _context.Tarefas.Remove(tarefa);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TarefaExists(int id)
        {
          return _context.Tarefas.Any(e => e.TarefaId == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <img src="~/imagem/tarefas.jpg" />
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ListaTarefas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ListaTarefas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lista De Tarefas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tarefas" asp-action="Index">Tarefas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Lista de Tarefas
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Tarefas/Create.cshtml
@model ListaTarefas.Models.Tarefa

@{
    ViewData["Title"] = "Create";
}

<h4>Cadastrar Tarefas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Inicio" class="control-label"></label>
                <input asp-for="Inicio" class="form-control" />
                <span asp-validation-for="Inicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fim" class="control-label"></label>
                <input asp-for="Fim" class="form-control" />
                <span asp-validation-for="Fim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Importancia" class="control-label"></label>
                <input asp-for="Importancia" class="form-control" />
                <span asp-validation-for="Importancia" class="text-danger"></span>
            </div
            <br /><br />
            <div class="form-group">
                <input type="submit" value="Cadastrar" class="btn btn-primary" />  
                <a asp-action="Index" class="btn btn-secondary">Voltar</a>
            </div>            
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Tarefas/Delete.cshtml
@model ListaTarefas.Models.Tarefa

@{
    ViewData["Title"] = "Delete";
}

<h3>Deseja realmente excluir esta tarefa?</h3>
<div>    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Inicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Inicio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fim)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fim)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Importancia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Importancia)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TarefaId" />
        <input type="submit" value="Excluir" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-secondary">Voltar</a>
    </form>
</div>

Views/Tarefas/Details.cshtml
@model ListaTarefas.Models.Tarefa

@{
    ViewData["Title"] = "Details";
}

<div>
    <h4>Detalhes da Tarefa</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Inicio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Inicio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fim)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fim)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Importancia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Importancia)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.TarefaId" class="btn btn-primary">Editar</a> |
    <a asp-action="Index" class="btn btn-secondary">Voltar</a>
</div>

Views/Tarefas/Edit.cshtml
@model ListaTarefas.Models.Tarefa

@{
    ViewData["Title"] = "Edit";
}

<h4>Editar Tarefa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TarefaId" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Inicio" class="control-label"></label>
                <input asp-for="Inicio" class="form-control" />
                <span asp-validation-for="Inicio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fim" class="control-label"></label>
                <input asp-for="Fim" class="form-control" />
                <span asp-validation-for="Fim" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Importancia" class="control-label"></label>
                <input asp-for="Importancia" class="form-control" />
                <span asp-validation-for="Importancia" class="text-danger"></span>
            </div>
            <br /><br />
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Tarefas/Index.cshtml
@model IEnumerable<ListaTarefas.Models.Tarefa>

@{
    ViewData["Title"] = "Index";
}

<p>
    <a asp-action="Create" class="btn btn-primary">Adicionar Tarefa</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Inicio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fim)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Importancia)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Inicio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fim)
            </td>

            @if (item.Importancia == "Baixa")
            {
                <td class="text-info">
                    @Html.DisplayFor(modelItem => item.Importancia)
                </td>
            }

            @if (item.Importancia == "Média")
            {
                <td class="text-warning">
                    @Html.DisplayFor(modelItem => item.Importancia)
                </td>
            }

            @if (item.Importancia == "Crítica")
            {
                <td class="text-danger">
                    @Html.DisplayFor(modelItem => item.Importancia)
                </td>
            }
                        
            <td>
                <a asp-action="Edit" asp-route-id="@item.TarefaId" class="btn btn-warning">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.TarefaId" class="btn btn-success">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.TarefaId" class="btn btn-danger">Excluir</a>
            </td>
        </tr>
}
    </tbody>
</table>